spring:
  #配置模板信息
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5

  #配置数据源
  datasource:
    url: jdbc:mysql://39.108.150.106:3306/miaosha?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 121522
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 100
    maxWait: 60000
    filters: stat
    maxActive: 1000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false




#mybatis
mybatis:
  type-aliases-package: cn.lbin.miaosha.domain
  configuration:
    #开启驼峰映射
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 10000
  mapper-locations: classpath:mybatis/*.xml

#redis
redis:
  host: 39.108.150.106
  port: 6379
  password: 121522
  timeout: 30000
  pool-max-total: 1000
  pool-max-idle: 500
  pool-max-wait: 500
