spring:
  #配置静态文件缓存
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
      cache: true
      compressed: false
      enabled: true
      html-application-cache: true
    cache:
      cachecontrol:
        cache-public: true
        max-age: 2h
    static-locations: classpath:/static/
  #配置模板信息
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
  #配置数据源
  datasource:
    url: jdbc:mysql://******:3306/miaosha?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 121522
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 100
    maxWait: 60000
    filters: stat
    maxActive: 1000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  #rabbit
  rabbitmq:
    host: ********
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        #消费者数量
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0



#mybatis
mybatis:
  type-aliases-package: cn.lbin.miaosha.domain
  configuration:
    #开启驼峰映射
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 10000
  mapper-locations: classpath:mybatis/*.xml

#redis
redis:
  host: *************
  port: 6379
  password: 121522
  timeout: 10000
  pool-max-total: 1000
  pool-max-idle: 500
  pool-max-wait: 500

